### ISSUE TITLE
Help with CSS for Results

### ISSUE THREAD

**Issue by mborjon** [susanBuck/e2-fall20#105]
Hello @susanBuck and classmates,

I don't have any experience with CSS, so does anyone have thoughts on the following.  I was trying to add colors to my results as in the class video, but for some reason it is doing nothing.

**Here is the code which is in the index.blade.php file**

```blade

@if($results)

<div class='{{ $results['winner'] ? 'won' : 'lost' }}'>
    <p>You chose: {{ $results['choice']}}</p>

    @if($results['Tie'])
    It’s a tie.
    @elseif($results['winner'])
    Congratulations, you won!
    @else
    Sorry, you lost, please try again.
    @endif
</div>

@endif
```
**Here is the CSS code in the app.css file**

```css
#logo {
    width:300px;
}

.won {
    color: green;
}

.lost {
    color: red;

}
```
